import React from 'react';
import ReactMarkdown from 'react-markdown';
import { Bot, AlertTriangle, Terminal } from 'lucide-react';

interface EducationPanelProps {
  content: string;
  loading: boolean;
  analysis: string;
}

const EducationPanel: React.FC<EducationPanelProps> = ({ content, loading, analysis }) => {
  return (
    <div className="bg-cyber-panel border border-gray-700 rounded-lg p-6 flex flex-col h-full">
      <div className="flex items-center space-x-2 mb-4 text-cyber-accent">
        <Bot size={24} />
        <h2 className="text-xl font-bold font-mono">AI ANALYST</h2>
      </div>

      <div className="bg-black/40 border border-gray-800 rounded p-3 mb-4 font-mono text-xs text-cyber-warning flex items-start space-x-2">
        <Terminal size={16} className="mt-0.5 flex-shrink-0" />
        <p>{analysis}</p>
      </div>

      <div className="flex-1 overflow-y-auto pr-2">
        {loading ? (
            <div className="flex items-center justify-center h-32 space-x-2 text-cyber-accent">
                <div className="w-2 h-2 bg-cyber-accent rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
                <div className="w-2 h-2 bg-cyber-accent rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
                <div className="w-2 h-2 bg-cyber-accent rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
            </div>
        ) : (
          <div className="prose prose-invert prose-sm max-w-none">
            <ReactMarkdown
                components={{
                    h1: ({node, ...props}) => <h3 className="text-lg font-bold text-cyber-accent mb-2" {...props} />,
                    h2: ({node, ...props}) => <h4 className="text-md font-bold text-white mb-2" {...props} />,
                    h3: ({node, ...props}) => <h5 className="text-sm font-bold text-gray-300 mb-1" {...props} />,
                    ul: ({node, ...props}) => <ul className="list-disc pl-4 mb-2 space-y-1 text-gray-300" {...props} />,
                    li: ({node, ...props}) => <li className="text-sm" {...props} />,
                    p: ({node, ...props}) => <p className="text-sm text-gray-400 mb-4 leading-relaxed" {...props} />,
                    strong: ({node, ...props}) => <strong className="text-white font-semibold" {...props} />,
                }}
            >
                {content}
            </ReactMarkdown>
          </div>
        )}
      </div>
      
      <div className="mt-4 pt-4 border-t border-gray-700 flex items-center space-x-2 text-xs text-gray-500">
        <AlertTriangle size={12} />
        <p>Educational content generated by Gemini 2.5 Flash.</p>
      </div>
    </div>
  );
};

export default EducationPanel;
